appId: com.runner
windowsName: 运行器
configFile:
    - /Users/ll/Documents/workspace/quick_cmd/ui/xyj.yaml
    - config.yaml
    - xyj.yaml
    - xyj2.yaml
    - xyj24.yaml
    - xyj24aaaa.yaml
lastOpenedFile: config.yaml
workPaths:
    ACC-CLOUD: /Users/ll/Documents/workspace/xyj-acc-cloud
    HOME: "~"
    MVM: /Users/ll/Documents/Maven/apache-maven-3.6.1/bin/mvn
    XYJ-ACC: /Users/ll/Documents/workspace/xyjacc
    XYJ-ACC-CRON: /Users/ll/Documents/workspace/xyjacc-cron
machines:
    - encrypted_data: AqmCXKWPbbJ0sadelljJ3uKG0Hqp1l7RMWCYemxARvFFZdpO91dUyNRgd8rMSjrM5jxIxYinGEx9S6wPAFEDzyk2TUpGM18zPSLXe+bcxbRWWPTHkElpV8b1OXtfXioai/mtk5Oru8f1WEXmQOXDLp88CxHoo52OMPsHgvfwDoJ8QiKs11wHqQ==
      name: jz
      key_file: /Users/ll/.ssh/id_rsa
