appId: com.runner
windowsName: 运行器
configFile:
    - /Users/ll/Documents/workspace/quick_cmd/ui/xyj.yaml
    - /Users/ll/Documents/workspace/new_cmd/config.yaml
lastOpenedFile: /Users/ll/Documents/workspace/new_cmd/config.yaml
workPaths:
    ACC-CLOUD: /Users/ll/Documents/workspace/xyj-acc-cloud
    HOME: "~"
    MVM: /Users/ll/Documents/Maven/apache-maven-3.6.1/bin/mvn
    XYJ-ACC: /Users/ll/Documents/workspace/xyjacc
    XYJ-ACC-CRON: /Users/ll/Documents/workspace/xyjacc-cron
machines:
    - encrypted_data: bmKmZdz27Omg/bGF3320s3fatcEhCqp6CA3+QHozi/BGL+KHgl7qEZfOwYimEPc3y4i4v7roW6aYrNZ1qW6ETHuLBJ61ICAfJTAkRdfh4ay1TWRyvi/1LNKXeDPYljnTWApCiO6UWuYJiirXO55OIQs8hZehFAGTNbr+idwNpA==
      name: 196-dev
      key_file: /Users/ll/.ssh/id_rsa
    - encrypted_data: 7D/z8bpuptrEcfxwH7Sch0v0tqiRZJgDK1VSfbh0nTvRafV01yniiZjhTUhfHP8JHt7KN1SBbO5Vngylybm71o9nyls2cYikEtRnOQ5P0NUAHslIj5AC7tn842p9I8tmfmnN5HoQ/6tcGgbKZUipKsJA0wPzJ35Liw==
      name: jz
      key_file: /Users/ll/.ssh/id_rsa
