package mcp

import "strings"

func skillDoc(name, desc string, triggers []string, body string) builtinSkill {
	front := "---\nname: " + name + "\ndescription: " + desc + "\n触发词: " + strings.Join(triggers, ", ") + "\n---\n\n"
	return builtinSkill{Name: name, Description: desc, Triggers: triggers, Body: front + body}
}

func builtinSkills() []builtinSkill {
	t := func(xs ...string) []string { return xs }
	return []builtinSkill{
		skillDoc("linux-fundamentals", "Linux 基础运维：系统/进程/磁盘/网络/用户/cron", t("linux", "系统", "磁盘满", "进程", "内存", "负载", "df", "top", "ss", "netstat", "cron", "hostname"),
			"# Linux 基础\n\n优先用只读工具：system_info / disk_usage / port_check / service_status / tail_log。\n不够用再 ssh_exec。Windows 不要发 df/ss/systemctl。\n含 sudo 的命令会审批或被拒（未开 AI sudo）。\n"),
		skillDoc("systemd-service", "systemd 服务启停与排障", t("systemd", "systemctl", "服务", "重启服务", "unit"),
			"# systemd\n\n只读：service_status(server, service)。\n改状态用 ssh_exec：systemctl start/stop/restart <unit>，先征得用户确认。\n"),
		skillDoc("ssh-hardening", "SSH 加固与登录排障", t("ssh", "sshd", "加固", "PermitRootLogin", "失败登录"),
			"# SSH\n\n查端口 port_check；看配置 sftp_read /etc/ssh/sshd_config（敏感路径 ~/.ssh 禁止）。\n改 sshd 必须用户确认，改完 sshd -t 再 reload。\n"),
		skillDoc("iptables-firewalld", "防火墙：firewalld / iptables / ufw", t("防火墙", "firewalld", "iptables", "ufw", "安全组"),
			"# 防火墙\n\n先只读查规则。改规则会断连，必须用户确认。不要 iptables -F / ufw reset。\n公网 80/443 常在云安全组，不只是主机防火墙。\n"),
		skillDoc("selinux-apparmor", "SELinux / AppArmor 排障", t("selinux", "apparmor", "avc", "denied"),
			"# SELinux / AppArmor\n\n只读查 getenforce / aa-status。不要 setenforce 0 当常规方案。\n"),
		skillDoc("nginx-status", "Nginx 状态、配置与 reload", t("nginx", "ngx", "反代", "vhost"),
			"# Nginx\n\n建站优先 web_status / web_create_proxy / web_create_static，不要手装 nginx。\n查状态：service_status(nginx) 或 ssh_exec nginx -t。\n"),
		skillDoc("openresty-lua", "OpenResty 与 FlashShell 网站体系", t("openresty", "lua", "站点", "反代", "ssl", "证书"),
			"# OpenResty / 网站\n\n1. web_status 2. 未装则 web_install_openresty 3. web_create_proxy 或 web_create_static\n4. sftp_upload 静态产物 5. web_issue_ssl。证书进工作台，不要手搓 certbot。\n"),
		skillDoc("caddy-traefik", "Caddy / Traefik 反代", t("caddy", "traefik"),
			"# Caddy / Traefik\n\n能走 FlashShell web_* 就走 web_*。已有 Caddy/Traefik 再用 ssh_exec 查配置，改前备份。\n"),
		skillDoc("certbot-acme", "Let's Encrypt / ACME 证书", t("certbot", "acme", "letsencrypt", "证书", "ssl", "https"),
			"# 证书\n\n正道：web_issue_ssl（HTTP-01，域名解析到本机 + 放行 80）。证书进工作台并续期。\n"),
		skillDoc("docker-ps", "Docker / Compose 容器运维", t("docker", "compose", "容器", "镜像", "container"),
			"# Docker\n\n只读：ssh_exec 'docker ps -a' / 'docker info'。\n共享库用 install_app。应用部署走 deploy_upsert_target → dry_run → 确认 → deploy_run。\n不要 docker rm -f 用户没同意的容器。\n"),
		skillDoc("kubernetes-basics", "Kubernetes 基础排查", t("kubernetes", "k8s", "kubectl", "pod", "deployment"),
			"# Kubernetes\n\n先确认集群入口。只读 kubectl get/describe/logs。改资源先给用户看 YAML。\n"),
		skillDoc("portainer-ops", "Portainer 安装与接入台账", t("portainer"),
			"# Portainer\n\n装带密码服务用 install_with_secret，再 save_credential 登记 access_url。\n不要 ssh_exec 自己 openssl 出密码。\n"),
		skillDoc("1panel-ops", "1Panel 安装与运维", t("1panel", "1pctl", "宝塔"),
			"# 1Panel\n\n长安装 timeoutSecs=1800，用 install_with_secret。装完 list_installed_services / save_credential。\n"),
		skillDoc("mysql-ops", "MySQL 安装与备份要点", t("mysql", "mariadb", "慢查询"),
			"# MySQL\n\n共享实例：install_app(app=mysql)，label=MySQL，容器 flashshell-mysql。\n查询/改库用 ssh_exec（经隧道或本机端口），不要把密码写进命令。\n"),
		skillDoc("postgresql-ops", "PostgreSQL 安装与访问", t("postgres", "postgresql", "pgsql"),
			"# PostgreSQL\n\ninstall_app(app=postgres)。凭据 postgres_conn 入库。\n查询/改库用 ssh_exec，不要把密码写进命令。\n"),
		skillDoc("mongodb-ops", "MongoDB 安装与注意点", t("mongodb", "mongo"),
			"# MongoDB\n\ninstall_app(app=mongodb)。不要把密码写进 ssh_exec。\n"),
		skillDoc("redis-ops", "Redis 安装与运维", t("redis", "缓存"),
			"# Redis\n\ninstall_app(app=redis)。只读/写入用 ssh_exec redis-cli，不要把密码写进对话。\n"),
		skillDoc("clickhouse-ops", "ClickHouse 运维要点", t("clickhouse"),
			"# ClickHouse\n\n先 list_installed_services / port_check。改配置先备份。\n"),
		skillDoc("kafka-ops", "Kafka 基础排查", t("kafka", "topic", "consumer"),
			"# Kafka\n\n只读查进程/端口/日志。改 topic 先确认。\n"),
		skillDoc("rabbitmq-ops", "RabbitMQ 运维", t("rabbitmq", "amqp"),
			"# RabbitMQ\n\n查端口 5672/15672，看日志。改用户/vhost 需确认。\n"),
		skillDoc("minio-s3", "MinIO / S3 对象存储", t("minio", "s3", "对象存储"),
			"# MinIO\n\n凭据走 save_credential，不要把 secret 打进对话。\n"),
		skillDoc("nfs-smb-share", "NFS / SMB 共享", t("nfs", "smb", "cifs", "共享盘"),
			"# NFS/SMB\n\n只读查 mount / exports。改导出表先确认，避免把根目录共享出去。\n"),
		skillDoc("git-server", "Git 服务与仓库", t("git", "gitea", "gitlab", "仓库"),
			"# Git\n\n部署走 deploy_*。不要在服务器上硬重置用户没同意的仓库。\n"),
		skillDoc("jenkins-runner", "Jenkins 安装与任务", t("jenkins", "ci", "流水线"),
			"# Jenkins\n\n安装用 install_with_secret，timeoutSecs=1800。凭据入库。\n"),
		skillDoc("nodejs-pm2", "Node.js / PM2", t("node", "nodejs", "pm2", "npm", "pnpm"),
			"# Node\n\n生产默认 Docker compose。PM2 仅用户明确要原生时。\n"),
		skillDoc("python-venv-uwsgi", "Python venv / uWSGI / gunicorn", t("python", "venv", "uwsgi", "gunicorn", "django", "flask"),
			"# Python\n\n默认 Docker。改 uwsgi 配置先备份。\n"),
		skillDoc("php-fpm-ops", "PHP-FPM / 站点", t("php", "php-fpm", "laravel"),
			"# PHP\n\n查 php-fpm 状态与慢日志。改 php.ini 需确认。\n"),
		skillDoc("java-jvm-tuning", "JVM / Spring 内存与 GC", t("jvm", "java", "spring", "堆", "gc", "xmx"),
			"# JVM\n\n内存紧：加 swap + 容器 mem_limit + -Xmx。不要因为内存小就弃 Docker。\n"),
		skillDoc("prometheus-grafana", "Prometheus / Grafana", t("prometheus", "grafana", "监控", "告警"),
			"# 监控\n\n装 Grafana 用 install_with_secret，凭据入库。\n"),
		skillDoc("loki-promtail", "Loki / Promtail 日志", t("loki", "promtail", "日志采集"),
			"# Loki\n\n先看磁盘。改 scrape 配置先备份。\n"),
		skillDoc("log-investigation", "日志排查套路", t("日志", "报错", "error.log", "journalctl"),
			"# 日志\n\n优先 tail_log。journalctl 用 ssh_exec 且加 -n，避免交互。\n"),
		skillDoc("borgbackup-restic", "Borg / Restic 备份", t("borg", "restic", "备份"),
			"# 备份\n\n备份目录用 ~/.flashshell 远程工作区或用户指定路径，不要臆造 /data/backup。\n"),
		skillDoc("wireguard-vpn", "WireGuard VPN", t("wireguard", "wg", "vpn"),
			"# WireGuard\n\n改 wg0 会断隧道，必须用户确认。密钥不要打印到对话。\n"),
		skillDoc("ollama-vllm", "Ollama / vLLM", t("ollama", "vllm", "大模型", "gpu"),
			"# 本地模型\n\n先查磁盘/显存。拉模型很占空间，先报告再下手。\n"),
		skillDoc("reeve-app-deploy", "通用应用部署剧本（install_app + deploy_upsert_target）", t("部署", "上线", "发布", "deploy", "部署到", "部署项目", "docker部署", "全栈部署"),
			"# 用 FlashShell 部署任意应用\n\n先 evaluate_skills：有框架专属技能（如 ruoyi-plus-uniapp-deploy）就用它。\n纪律：走 install_app + deploy_upsert_target（compose 托管）+ dry_run + 用户确认 + deploy_run。\n禁止 ssh_exec 手写 compose / openssl 出 .env。\n共享 MySQL/Redis：install_app，容器 flashshell-<app>，绑 127.0.0.1。\nrelease.deployRoot 必须 /opt/flashshell/stacks/<应用标识>。\napp 容器 host 网络，DB_HOST=127.0.0.1。同域 SPA：domain 设在前端 static-openresty。\n"),
		skillDoc("ruoyi-plus-uniapp-deploy", "RuoYi-Plus + UniApp 同域部署", t("ruoyi", "若依", "uniapp", "ryplus", "ryplus_uni"),
			"# RuoYi-Plus UniApp\n\n用 reeve-app-deploy 通用纪律。应用标识取 app.id（如 ryplus_uni）。\n后端 docker-compose 不设 domain，只听 127.0.0.1:<port>。\n前端 static-openresty：domain + https + vars.apiProxyPort / apiProxyPrefix。\ncompose.db mode=create 建库账号并登记独立 mysql_conn。\n"),
	}
}
