// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMachine(arg1) {
  return window['go']['app']['App']['AddMachine'](arg1);
}

export function ClearOutput() {
  return window['go']['app']['App']['ClearOutput']();
}

export function DeleteMachine(arg1) {
  return window['go']['app']['App']['DeleteMachine'](arg1);
}

export function ExecuteCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteCommand'](arg1, arg2, arg3);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetMachines() {
  return window['go']['app']['App']['GetMachines']();
}

export function GetOutput() {
  return window['go']['app']['App']['GetOutput']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function StopAllCommands() {
  return window['go']['app']['App']['StopAllCommands']();
}

export function StopCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['StopCommand'](arg1, arg2, arg3);
}

export function TestMachineConnection(arg1) {
  return window['go']['app']['App']['TestMachineConnection'](arg1);
}

export function UpdateMachine(arg1, arg2) {
  return window['go']['app']['App']['UpdateMachine'](arg1, arg2);
}
