// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';
import {app} from '../models';
import {menu} from '../models';
import {data} from '../models';

export function AddMachine(arg1:define.Machine):Promise<void>;

export function AddMachineGroup(arg1:string):Promise<void>;

export function AddMachineWithEvent(arg1:define.Machine):Promise<void>;

export function AddWorkPath(arg1:string,arg2:string):Promise<void>;

export function AddWorkPathWithEvent(arg1:string,arg2:string):Promise<void>;

export function ApplyShellCd(arg1:string,arg2:string,arg3:string):Promise<string>;

export function BroadcastShellInput(arg1:Array<string>,arg2:string):Promise<void>;

export function CheckForUpdates():Promise<app.UpdateCheckResult>;

export function ClearFinishedShellTransfers():Promise<void>;

export function ClearMachineSensitiveData(arg1:string):Promise<void>;

export function ClearOutput():Promise<void>;

export function ClearShellHistory():Promise<void>;

export function ClearShellOutput(arg1:string):Promise<void>;

export function ConfirmQuit():Promise<void>;

export function ConnectLocalShell(arg1:string):Promise<string>;

export function ConnectShell(arg1:string):Promise<string>;

export function CreateApplicationMenu():Promise<menu.Menu>;

export function CreateMachine(arg1:define.Machine,arg2:define.SensitiveData):Promise<string>;

export function DeleteMachine(arg1:string):Promise<void>;

export function DeleteMachineGroup(arg1:string):Promise<void>;

export function DeleteMachineWithEvent(arg1:string):Promise<void>;

export function DeleteShellFile(arg1:string,arg2:string):Promise<void>;

export function DeleteWorkPath(arg1:string):Promise<void>;

export function DeleteWorkPathWithEvent(arg1:string):Promise<void>;

export function DisconnectShell(arg1:string):Promise<void>;

export function DownloadUpdate():Promise<app.UpdateDownloadResult>;

export function ExecuteCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteShellCommand(arg1:string,arg2:string):Promise<void>;

export function ExecuteSubProject(arg1:string,arg2:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetConfig():Promise<define.Root>;

export function GetConfigFiles():Promise<Array<string>>;

export function GetConfigForRefresh():Promise<define.Root>;

export function GetCurrentConfigPath():Promise<string>;

export function GetExecutionLogs(arg1:number):Promise<Array<data.LogEntry>>;

export function GetGlobalAccounts():Promise<Array<data.GlobalAccountDTO>>;

export function GetGlobalConfig():Promise<data.GlobalConfig>;

export function GetGlobalConfigForRefresh():Promise<data.GlobalConfig>;

export function GetMachineGroups():Promise<Array<string>>;

export function GetMachineSensitiveData(arg1:string):Promise<define.SensitiveData>;

export function GetMachines():Promise<Array<define.Machine>>;

export function GetOutput():Promise<Array<string>>;

export function GetSessionInfo():Promise<data.SessionState>;

export function GetShellDownloadDir():Promise<string>;

export function GetShellHistory():Promise<Array<define.ShellHistoryRecord>>;

export function GetShellMonitor(arg1:string,arg2:string):Promise<define.ShellMonitorSnapshot>;

export function GetShellPtyCwd(arg1:string):Promise<string>;

export function GetShellRemoteHome(arg1:string):Promise<string>;

export function GetShellRemotePwd(arg1:string):Promise<string>;

export function GetShellSessions():Promise<Array<define.ShellStatus>>;

export function GetShellStatus():Promise<define.ShellStatus>;

export function GetShellSystemInfo(arg1:string):Promise<define.ShellSystemInfo>;

export function GetShellTunnelStatus(arg1:string):Promise<Array<define.SSHTunnelStatus>>;

export function GetShortcutSettings():Promise<data.ShortcutSettings>;

export function GetSkippedUpdateVersion():Promise<string>;

export function GetStatus():Promise<define.CommandStatus>;

export function GetSubProjectStatus():Promise<define.SubProjectStatus>;

export function GetSystemSettings():Promise<data.GlobalConfig>;

export function GetThemeSettings():Promise<data.ThemeSettings>;

export function GetWorkPaths():Promise<Record<string, string>>;

export function ImportFinalShellPick(arg1:string,arg2:string):Promise<data.MachineImportResult>;

export function ImportXshellFromFile(arg1:string,arg2:string,arg3:string):Promise<data.MachineImportResult>;

export function ImportXshellFromFolder(arg1:string,arg2:string,arg3:string):Promise<data.MachineImportResult>;

export function ImportXshellPick(arg1:string,arg2:string):Promise<data.MachineImportResult>;

export function ListShellFiles(arg1:string,arg2:string,arg3:boolean):Promise<Array<define.SftpEntry>>;

export function ListShellTransfers():Promise<Array<define.SftpTransferRecord>>;

export function ListSystemFonts():Promise<Array<app.SystemFontInfo>>;

export function NewWindow():Promise<void>;

export function OpenAbout():Promise<void>;

export function OpenConfigEditor():Promise<void>;

export function OpenConnectionManager():Promise<void>;

export function OpenCurrentConfigWithEvent():Promise<void>;

export function OpenDownloadsDirectory():Promise<void>;

export function OpenExecutionHistory():Promise<void>;

export function OpenExecutionLog(arg1:string):Promise<void>;

export function OpenGlobalConfigWithEvent():Promise<void>;

export function OpenMachineConfig():Promise<void>;

export function OpenReleaseURL(arg1:string):Promise<void>;

export function OpenShellDownloadDir():Promise<void>;

export function OpenSystemSettings():Promise<void>;

export function OpenWorkPathConfig():Promise<void>;

export function PauseShellTransfer(arg1:string):Promise<void>;

export function PickShellUploadFolder():Promise<string>;

export function PickShellUploadPaths():Promise<Array<string>>;

export function ReadExecutionLog(arg1:string):Promise<string>;

export function ReconnectShell(arg1:string):Promise<string>;

export function RefreshConfigMenu():Promise<void>;

export function RefreshConfigMenuWithEvent():Promise<void>;

export function RemoveShellHistory(arg1:string,arg2:string):Promise<void>;

export function RemoveShellTransfer(arg1:string):Promise<void>;

export function RenameMachineGroup(arg1:string,arg2:string):Promise<void>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function ResolveShellPath(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ResumeShellTransfer(arg1:string):Promise<void>;

export function SaveConfig(arg1:define.Root):Promise<void>;

export function SaveGlobalAccounts(arg1:Array<data.GlobalAccount>):Promise<void>;

export function SaveGlobalAccountsFromDTO(arg1:Array<data.GlobalAccountDTO>):Promise<void>;

export function SaveGlobalConfig(arg1:data.GlobalConfig):Promise<void>;

export function SaveShortcutSettings(arg1:data.ShortcutSettings):Promise<void>;

export function SaveSystemSettings(arg1:data.GlobalConfig):Promise<void>;

export function SaveThemeSettings(arg1:data.ThemeSettings):Promise<void>;

export function SelectKeyFile():Promise<string>;

export function SelectXshellFile():Promise<string>;

export function SelectXshellFolder():Promise<string>;

export function SendShellInput(arg1:string,arg2:string):Promise<void>;

export function SendShellInterrupt(arg1:string):Promise<void>;

export function SetMachineSensitiveData(arg1:string,arg2:define.SensitiveData):Promise<void>;

export function ShellDirExists(arg1:string,arg2:string):Promise<boolean>;

export function SkipUpdateVersion(arg1:string):Promise<void>;

export function StartShellDownload(arg1:string,arg2:string):Promise<string>;

export function StartShellUpload(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StopAllCommands():Promise<void>;

export function StopAllSubProjects():Promise<void>;

export function StopCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopShellCommand(arg1:string):Promise<void>;

export function StopSubProject(arg1:string,arg2:string):Promise<void>;

export function SwitchConfigFileWithEvent(arg1:string):Promise<void>;

export function SyncShellCwd(arg1:string,arg2:string):Promise<string>;

export function TestMachineConnection(arg1:string):Promise<void>;

export function TestMachineDraftConnection(arg1:define.Machine,arg2:define.SensitiveData):Promise<void>;

export function TestProxyConnection(arg1:data.ProxySettings,arg2:string):Promise<string>;

export function UpdateApplicationMenu():Promise<void>;

export function UpdateMachine(arg1:string,arg2:define.Machine):Promise<void>;

export function UpdateMachineGroup(arg1:string,arg2:string):Promise<void>;

export function UpdateMachineWithEvent(arg1:string,arg2:define.Machine):Promise<void>;

export function UpdateWorkPath(arg1:string,arg2:string):Promise<void>;

export function UpdateWorkPathWithEvent(arg1:string,arg2:string):Promise<void>;
