// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';
import {context} from '../models';
import {data} from '../models';

export function AddMachine(arg1:define.Machine):Promise<void>;

export function ClearOutput():Promise<void>;

export function DeleteMachine(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteSubProject(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<define.Root>;

export function GetConfigFiles():Promise<Array<string>>;

export function GetCtx():Promise<context.Context>;

export function GetGlobalConfig():Promise<data.GlobalConfig>;

export function GetMachines():Promise<Array<define.Machine>>;

export function GetOutput():Promise<Array<string>>;

export function GetStatus():Promise<define.CommandStatus>;

export function GetSubProjectStatus():Promise<define.SubProjectStatus>;

export function RefreshUI():Promise<void>;

export function SaveConfig(arg1:define.Root):Promise<void>;

export function SaveGlobalConfig(arg1:data.GlobalConfig):Promise<void>;

export function StopAllCommands():Promise<void>;

export function StopAllSubProjects():Promise<void>;

export function StopCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopSubProject(arg1:string,arg2:string):Promise<void>;

export function SwitchConfigFile(arg1:string):Promise<void>;

export function TestMachineConnection(arg1:string):Promise<void>;

export function UpdateMachine(arg1:string,arg2:define.Machine):Promise<void>;
