// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {define} from '../models';
import {menu} from '../models';
import {data} from '../models';

export function AddMachine(arg1:define.Machine):Promise<void>;

export function AddMachineWithEvent(arg1:define.Machine):Promise<void>;

export function AddWorkPath(arg1:string,arg2:string):Promise<void>;

export function AddWorkPathWithEvent(arg1:string,arg2:string):Promise<void>;

export function ClearMachineSensitiveData(arg1:string):Promise<void>;

export function ClearOutput():Promise<void>;

export function CreateApplicationMenu():Promise<menu.Menu>;

export function DeleteMachine(arg1:string):Promise<void>;

export function DeleteMachineWithEvent(arg1:string):Promise<void>;

export function DeleteWorkPath(arg1:string):Promise<void>;

export function DeleteWorkPathWithEvent(arg1:string):Promise<void>;

export function ExecuteCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExecuteSubProject(arg1:string,arg2:string):Promise<void>;

export function GetConfig():Promise<define.Root>;

export function GetConfigFiles():Promise<Array<string>>;

export function GetConfigForRefresh():Promise<define.Root>;

export function GetGlobalConfig():Promise<data.GlobalConfig>;

export function GetGlobalConfigForRefresh():Promise<data.GlobalConfig>;

export function GetMachineSensitiveData(arg1:string):Promise<define.SensitiveData>;

export function GetMachines():Promise<Array<define.Machine>>;

export function GetOutput():Promise<Array<string>>;

export function GetStatus():Promise<define.CommandStatus>;

export function GetSubProjectStatus():Promise<define.SubProjectStatus>;

export function GetWorkPaths():Promise<Record<string, string>>;

export function OpenCurrentConfigWithEvent():Promise<void>;

export function OpenMachineConfig():Promise<void>;

export function OpenWorkPathConfig():Promise<void>;

export function RefreshConfigMenu():Promise<void>;

export function RefreshConfigMenuWithEvent():Promise<void>;

export function SaveConfig(arg1:define.Root):Promise<void>;

export function SaveGlobalConfig(arg1:data.GlobalConfig):Promise<void>;

export function SelectKeyFile():Promise<string>;

export function SetMachineSensitiveData(arg1:string,arg2:define.SensitiveData):Promise<void>;

export function StopAllCommands():Promise<void>;

export function StopAllSubProjects():Promise<void>;

export function StopCommand(arg1:string,arg2:string,arg3:string):Promise<void>;

export function StopSubProject(arg1:string,arg2:string):Promise<void>;

export function SwitchConfigFileWithEvent(arg1:string):Promise<void>;

export function TestMachineConnection(arg1:string):Promise<void>;

export function UpdateApplicationMenu():Promise<void>;

export function UpdateMachine(arg1:string,arg2:define.Machine):Promise<void>;

export function UpdateMachineWithEvent(arg1:string,arg2:define.Machine):Promise<void>;

export function UpdateWorkPath(arg1:string,arg2:string):Promise<void>;

export function UpdateWorkPathWithEvent(arg1:string,arg2:string):Promise<void>;
