// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMachine(arg1) {
  return window['go']['app']['App']['AddMachine'](arg1);
}

export function AddMachineWithEvent(arg1) {
  return window['go']['app']['App']['AddMachineWithEvent'](arg1);
}

export function AddWorkPath(arg1, arg2) {
  return window['go']['app']['App']['AddWorkPath'](arg1, arg2);
}

export function AddWorkPathWithEvent(arg1, arg2) {
  return window['go']['app']['App']['AddWorkPathWithEvent'](arg1, arg2);
}

export function ClearMachineSensitiveData(arg1) {
  return window['go']['app']['App']['ClearMachineSensitiveData'](arg1);
}

export function ClearOutput() {
  return window['go']['app']['App']['ClearOutput']();
}

export function CreateApplicationMenu() {
  return window['go']['app']['App']['CreateApplicationMenu']();
}

export function DeleteMachine(arg1) {
  return window['go']['app']['App']['DeleteMachine'](arg1);
}

export function DeleteMachineWithEvent(arg1) {
  return window['go']['app']['App']['DeleteMachineWithEvent'](arg1);
}

export function DeleteWorkPath(arg1) {
  return window['go']['app']['App']['DeleteWorkPath'](arg1);
}

export function DeleteWorkPathWithEvent(arg1) {
  return window['go']['app']['App']['DeleteWorkPathWithEvent'](arg1);
}

export function ExecuteCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['ExecuteCommand'](arg1, arg2, arg3);
}

export function ExecuteSubProject(arg1, arg2) {
  return window['go']['app']['App']['ExecuteSubProject'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetConfigFiles() {
  return window['go']['app']['App']['GetConfigFiles']();
}

export function GetConfigForRefresh() {
  return window['go']['app']['App']['GetConfigForRefresh']();
}

export function GetGlobalConfig() {
  return window['go']['app']['App']['GetGlobalConfig']();
}

export function GetGlobalConfigForRefresh() {
  return window['go']['app']['App']['GetGlobalConfigForRefresh']();
}

export function GetMachineSensitiveData(arg1) {
  return window['go']['app']['App']['GetMachineSensitiveData'](arg1);
}

export function GetMachines() {
  return window['go']['app']['App']['GetMachines']();
}

export function GetOutput() {
  return window['go']['app']['App']['GetOutput']();
}

export function GetStatus() {
  return window['go']['app']['App']['GetStatus']();
}

export function GetSubProjectStatus() {
  return window['go']['app']['App']['GetSubProjectStatus']();
}

export function GetWorkPaths() {
  return window['go']['app']['App']['GetWorkPaths']();
}

export function OpenCurrentConfigWithEvent() {
  return window['go']['app']['App']['OpenCurrentConfigWithEvent']();
}

export function OpenMachineConfig() {
  return window['go']['app']['App']['OpenMachineConfig']();
}

export function OpenWorkPathConfig() {
  return window['go']['app']['App']['OpenWorkPathConfig']();
}

export function RefreshConfigMenu() {
  return window['go']['app']['App']['RefreshConfigMenu']();
}

export function RefreshConfigMenuWithEvent() {
  return window['go']['app']['App']['RefreshConfigMenuWithEvent']();
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SaveGlobalConfig(arg1) {
  return window['go']['app']['App']['SaveGlobalConfig'](arg1);
}

export function SelectKeyFile() {
  return window['go']['app']['App']['SelectKeyFile']();
}

export function SetMachineSensitiveData(arg1, arg2) {
  return window['go']['app']['App']['SetMachineSensitiveData'](arg1, arg2);
}

export function StopAllCommands() {
  return window['go']['app']['App']['StopAllCommands']();
}

export function StopAllSubProjects() {
  return window['go']['app']['App']['StopAllSubProjects']();
}

export function StopCommand(arg1, arg2, arg3) {
  return window['go']['app']['App']['StopCommand'](arg1, arg2, arg3);
}

export function StopSubProject(arg1, arg2) {
  return window['go']['app']['App']['StopSubProject'](arg1, arg2);
}

export function SwitchConfigFileWithEvent(arg1) {
  return window['go']['app']['App']['SwitchConfigFileWithEvent'](arg1);
}

export function TestMachineConnection(arg1) {
  return window['go']['app']['App']['TestMachineConnection'](arg1);
}

export function UpdateApplicationMenu() {
  return window['go']['app']['App']['UpdateApplicationMenu']();
}

export function UpdateMachine(arg1, arg2) {
  return window['go']['app']['App']['UpdateMachine'](arg1, arg2);
}

export function UpdateMachineWithEvent(arg1, arg2) {
  return window['go']['app']['App']['UpdateMachineWithEvent'](arg1, arg2);
}

export function UpdateWorkPath(arg1, arg2) {
  return window['go']['app']['App']['UpdateWorkPath'](arg1, arg2);
}

export function UpdateWorkPathWithEvent(arg1, arg2) {
  return window['go']['app']['App']['UpdateWorkPathWithEvent'](arg1, arg2);
}
